---
code: WPS437
internalName: RedundantFinallyViolation
title: Found finally in try block without except
---

Forbids to use `finally` in `try` block without `except` block.

## Reasoning
This rule will reduce complexity and improve readability.

## Solution
Refactor your `try` logic. Replace the `try-finally` statement with
a `with` statement.

## Example

    # Correct:
    with open("filename") as f:
        f.write(...)
    
    # Wrong:
    try:
        f = open("filename")
        f.write(...)
    finally:
        f.close()

<div class="versionadded">

0.3.0

</div>